# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aicandy
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sls-aicandy-backend

provider:
  name: aws
  runtime: nodejs20.x

  apiGateway:
    apiKeys:
      - name: aicandy-api


functions:
  app:
    handler: handler.handler

    events:
      - http:
          path: /public
          method: get

      - http:
          path: /private
          method: get
          private: true