# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aicandy
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sls-aicandy-backend

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs20.x

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:us-east-1:*:table/AiCandyReportTable

  apiGateway:
    apiKeys:
      - name: aicandy-api

  environment:
    RDS_HOSTNAME: legendei-app.cgaek3spfsqe.us-east-1.rds.amazonaws.com
    RDS_USERNAME: admin
    RDS_PASSWORD: "u#JP6729"
    RDS_PORT: 3306
    DATABASE: legendei0-app

functions:
  app:
    handler: src/index.handler
    timeout: 30
    events:
      - http:
          path: /companies
          method: get
          private: false

      - http:
          path: /companies/{cvm_code}
          method: get
          private: false

      - http:
          path: /companies/{cvm_code}/webcasts
          method: get
          private: false

      - http:
          path: /companies/{cvm_code}/webcasts/{id}
          method: get
          private: false

    vpc:
      securityGroupIds:
        - sg-0a5e8ca68095b1ee6
      subnetIds:
        - subnet-b7b40886
  
# resources: # CloudFormation template syntax
#   Resources:
#     usersTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: AiCandyReportTable
#         AttributeDefinitions:
#           - AttributeName: summary
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: S
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1

plugins:
  - serverless-offline
